services:
  trading_bot:
    build:
      context: ./cmd/trading_bot
      dockerfile: Dockerfile
    init: true
    depends_on:
      migrator:
        condition: service_completed_successfully

  migrator:
    build:
      context: ./cmd/migrator
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.5-alpine3.21
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password_secret
      POSTGRES_USER_FILE: /run/secrets/db_user_secret
      POSTGRES_DB_FILE: /run/secrets/db_name_secret
    secrets:
      - db_password_secret
      - db_user_secret
      - db_name_secret

secrets:
  db_password_secret:
    file: ./secrets/db_password.txt
  db_user_secret:
    file: ./secrets/db_user.txt
  db_name_secret:
    file: ./secrets/db_name.txt

