// Code generated by MockGen. DO NOT EDIT.
// Source: strategy.go

// Package strategy is a generated GoMock package.
package strategy

import (
	reflect "reflect"
	datastruct "trading_bot/internal/service/datastruct"

	gomock "github.com/golang/mock/gomock"
)

// MockIStorage is a mock of IStorage interface.
type MockIStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIStorageMockRecorder
}

// MockIStorageMockRecorder is the mock recorder for MockIStorage.
type MockIStorageMockRecorder struct {
	mock *MockIStorage
}

// NewMockIStorage creates a new mock instance.
func NewMockIStorage(ctrl *gomock.Controller) *MockIStorage {
	mock := &MockIStorage{ctrl: ctrl}
	mock.recorder = &MockIStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStorage) EXPECT() *MockIStorageMockRecorder {
	return m.recorder
}

// GetHighestExecutedBuyOrder mocks base method.
func (m *MockIStorage) GetHighestExecutedBuyOrder(trId string, instrInfo *datastruct.InstrumentInfo) (*datastruct.Order, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHighestExecutedBuyOrder", trId, instrInfo)
	ret0, _ := ret[0].(*datastruct.Order)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetHighestExecutedBuyOrder indicates an expected call of GetHighestExecutedBuyOrder.
func (mr *MockIStorageMockRecorder) GetHighestExecutedBuyOrder(trId, instrInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHighestExecutedBuyOrder", reflect.TypeOf((*MockIStorage)(nil).GetHighestExecutedBuyOrder), trId, instrInfo)
}

// GetLatestExecutedSellOrder mocks base method.
func (m *MockIStorage) GetLatestExecutedSellOrder(trId string, instrInfo *datastruct.InstrumentInfo) (*datastruct.Order, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestExecutedSellOrder", trId, instrInfo)
	ret0, _ := ret[0].(*datastruct.Order)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLatestExecutedSellOrder indicates an expected call of GetLatestExecutedSellOrder.
func (mr *MockIStorageMockRecorder) GetLatestExecutedSellOrder(trId, instrInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestExecutedSellOrder", reflect.TypeOf((*MockIStorage)(nil).GetLatestExecutedSellOrder), trId, instrInfo)
}

// GetLowestExecutedBuyOrder mocks base method.
func (m *MockIStorage) GetLowestExecutedBuyOrder(trId string, instrInfo *datastruct.InstrumentInfo) (*datastruct.Order, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLowestExecutedBuyOrder", trId, instrInfo)
	ret0, _ := ret[0].(*datastruct.Order)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLowestExecutedBuyOrder indicates an expected call of GetLowestExecutedBuyOrder.
func (mr *MockIStorageMockRecorder) GetLowestExecutedBuyOrder(trId, instrInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLowestExecutedBuyOrder", reflect.TypeOf((*MockIStorage)(nil).GetLowestExecutedBuyOrder), trId, instrInfo)
}

// GetMaximum mocks base method.
func (m *MockIStorage) GetMaximum(traderUid string, instrInfo *datastruct.InstrumentInfo) (*datastruct.Quotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaximum", traderUid, instrInfo)
	ret0, _ := ret[0].(*datastruct.Quotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaximum indicates an expected call of GetMaximum.
func (mr *MockIStorageMockRecorder) GetMaximum(traderUid, instrInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaximum", reflect.TypeOf((*MockIStorage)(nil).GetMaximum), traderUid, instrInfo)
}

// GetMinimum mocks base method.
func (m *MockIStorage) GetMinimum(traderUid string, instrInfo *datastruct.InstrumentInfo) (*datastruct.Quotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinimum", traderUid, instrInfo)
	ret0, _ := ret[0].(*datastruct.Quotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinimum indicates an expected call of GetMinimum.
func (mr *MockIStorageMockRecorder) GetMinimum(traderUid, instrInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinimum", reflect.TypeOf((*MockIStorage)(nil).GetMinimum), traderUid, instrInfo)
}

// GetUnsoldOrdersAmount mocks base method.
func (m *MockIStorage) GetUnsoldOrdersAmount(trId string, instrInfo *datastruct.InstrumentInfo) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnsoldOrdersAmount", trId, instrInfo)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnsoldOrdersAmount indicates an expected call of GetUnsoldOrdersAmount.
func (mr *MockIStorageMockRecorder) GetUnsoldOrdersAmount(trId, instrInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnsoldOrdersAmount", reflect.TypeOf((*MockIStorage)(nil).GetUnsoldOrdersAmount), trId, instrInfo)
}

// IsMinMaxSet mocks base method.
func (m *MockIStorage) IsMinMaxSet(traderUid string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMinMaxSet", traderUid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMinMaxSet indicates an expected call of IsMinMaxSet.
func (mr *MockIStorageMockRecorder) IsMinMaxSet(traderUid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMinMaxSet", reflect.TypeOf((*MockIStorage)(nil).IsMinMaxSet), traderUid)
}

// MakeNewOrder mocks base method.
func (m *MockIStorage) MakeNewOrder(arg0 *datastruct.InstrumentInfo, arg1 *datastruct.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeNewOrder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MakeNewOrder indicates an expected call of MakeNewOrder.
func (mr *MockIStorageMockRecorder) MakeNewOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeNewOrder", reflect.TypeOf((*MockIStorage)(nil).MakeNewOrder), arg0, arg1)
}

// RemoveOrder mocks base method.
func (m *MockIStorage) RemoveOrder(instrInfo *datastruct.InstrumentInfo, order *datastruct.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOrder", instrInfo, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveOrder indicates an expected call of RemoveOrder.
func (mr *MockIStorageMockRecorder) RemoveOrder(instrInfo, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOrder", reflect.TypeOf((*MockIStorage)(nil).RemoveOrder), instrInfo, order)
}

// UpdateMaximum mocks base method.
func (m *MockIStorage) UpdateMaximum(traderUid string, instrInfo *datastruct.InstrumentInfo, price *datastruct.Quotation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMaximum", traderUid, instrInfo, price)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMaximum indicates an expected call of UpdateMaximum.
func (mr *MockIStorageMockRecorder) UpdateMaximum(traderUid, instrInfo, price interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMaximum", reflect.TypeOf((*MockIStorage)(nil).UpdateMaximum), traderUid, instrInfo, price)
}

// UpdateMinimum mocks base method.
func (m *MockIStorage) UpdateMinimum(traderUid string, instrInfo *datastruct.InstrumentInfo, price *datastruct.Quotation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMinimum", traderUid, instrInfo, price)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMinimum indicates an expected call of UpdateMinimum.
func (mr *MockIStorageMockRecorder) UpdateMinimum(traderUid, instrInfo, price interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMinimum", reflect.TypeOf((*MockIStorage)(nil).UpdateMinimum), traderUid, instrInfo, price)
}

// MockIBroker is a mock of IBroker interface.
type MockIBroker struct {
	ctrl     *gomock.Controller
	recorder *MockIBrokerMockRecorder
}

// MockIBrokerMockRecorder is the mock recorder for MockIBroker.
type MockIBrokerMockRecorder struct {
	mock *MockIBroker
}

// NewMockIBroker creates a new mock instance.
func NewMockIBroker(ctrl *gomock.Controller) *MockIBroker {
	mock := &MockIBroker{ctrl: ctrl}
	mock.recorder = &MockIBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBroker) EXPECT() *MockIBrokerMockRecorder {
	return m.recorder
}

// GetCurrentPosPrice mocks base method.
func (m *MockIBroker) GetCurrentPosPrice(traderUid, accountId string, instrInfo *datastruct.InstrumentInfo) (*datastruct.Quotation, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentPosPrice", traderUid, accountId, instrInfo)
	ret0, _ := ret[0].(*datastruct.Quotation)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCurrentPosPrice indicates an expected call of GetCurrentPosPrice.
func (mr *MockIBrokerMockRecorder) GetCurrentPosPrice(traderUid, accountId, instrInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentPosPrice", reflect.TypeOf((*MockIBroker)(nil).GetCurrentPosPrice), traderUid, accountId, instrInfo)
}
