{
 "title": "Golden Impeller",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Prices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  price,\r\n  ticker\r\nFROM price_history\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  price,\r\n  trader_id,\r\n  action\r\nFROM\r\n  orders_history\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp,\r\n  message,\r\n  details\r\nFROM logs"
    }
   ]
  }
 ]
}