// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bdtstf.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteOrderForInstrumentOfTrader = `-- name: DeleteOrderForInstrumentOfTrader :exec
DELETE FROM orders
WHERE instrument_id = $1
	AND trader_id = $2
	AND order_id = $3
`

type DeleteOrderForInstrumentOfTraderParams struct {
	InstrumentID int32
	TraderID     string
	OrderID      string
}

func (q *Queries) DeleteOrderForInstrumentOfTrader(ctx context.Context, arg DeleteOrderForInstrumentOfTraderParams) error {
	_, err := q.db.ExecContext(ctx, deleteOrderForInstrumentOfTrader, arg.InstrumentID, arg.TraderID, arg.OrderID)
	return err
}

const getHighestExecutedBuyOrder = `-- name: GetHighestExecutedBuyOrder :one
SELECT 
    id,
    created_at,
    completed_at,
    order_id,
    direction,
    exec_report_status,
    price_units,
    price_nano,
    lots_requested,
    lots_executed,
    additional_info
FROM orders
WHERE instrument_id = $1
    AND direction = 'BUY'
    AND exec_report_status = 'FILL'
    AND trader_id = $2
    AND order_id_ref IS NULL
ORDER BY price_units DESC, price_nano DESC
LIMIT 1
`

type GetHighestExecutedBuyOrderParams struct {
	InstrumentID int32
	TraderID     string
}

type GetHighestExecutedBuyOrderRow struct {
	ID               int32
	CreatedAt        sql.NullTime
	CompletedAt      sql.NullTime
	OrderID          string
	Direction        string
	ExecReportStatus string
	PriceUnits       int64
	PriceNano        int32
	LotsRequested    int64
	LotsExecuted     int64
	AdditionalInfo   sql.NullString
}

func (q *Queries) GetHighestExecutedBuyOrder(ctx context.Context, arg GetHighestExecutedBuyOrderParams) (GetHighestExecutedBuyOrderRow, error) {
	row := q.db.QueryRowContext(ctx, getHighestExecutedBuyOrder, arg.InstrumentID, arg.TraderID)
	var i GetHighestExecutedBuyOrderRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.OrderID,
		&i.Direction,
		&i.ExecReportStatus,
		&i.PriceUnits,
		&i.PriceNano,
		&i.LotsRequested,
		&i.LotsExecuted,
		&i.AdditionalInfo,
	)
	return i, err
}

const getLatestExecutedSellOrder = `-- name: GetLatestExecutedSellOrder :one
SELECT 
    id,
    created_at,
    completed_at,
    order_id,
    direction,
    exec_report_status,
    price_units,
    price_nano,
    lots_requested,
    lots_executed,
    additional_info
FROM orders
WHERE instrument_id = $1
    AND direction = 'SELL'
    AND exec_report_status = 'FILL'
    AND trader_id = $2
ORDER BY completed_at DESC
LIMIT 1
`

type GetLatestExecutedSellOrderParams struct {
	InstrumentID int32
	TraderID     string
}

type GetLatestExecutedSellOrderRow struct {
	ID               int32
	CreatedAt        sql.NullTime
	CompletedAt      sql.NullTime
	OrderID          string
	Direction        string
	ExecReportStatus string
	PriceUnits       int64
	PriceNano        int32
	LotsRequested    int64
	LotsExecuted     int64
	AdditionalInfo   sql.NullString
}

func (q *Queries) GetLatestExecutedSellOrder(ctx context.Context, arg GetLatestExecutedSellOrderParams) (GetLatestExecutedSellOrderRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestExecutedSellOrder, arg.InstrumentID, arg.TraderID)
	var i GetLatestExecutedSellOrderRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.OrderID,
		&i.Direction,
		&i.ExecReportStatus,
		&i.PriceUnits,
		&i.PriceNano,
		&i.LotsRequested,
		&i.LotsExecuted,
		&i.AdditionalInfo,
	)
	return i, err
}

const getLowestExecutedBuyOrder = `-- name: GetLowestExecutedBuyOrder :one
SELECT 
    id,
    created_at, 
    completed_at, 
    order_id, 
    direction, 
    exec_report_status,
    price_units, 
    price_nano, 
    lots_requested,
    lots_executed, 
    additional_info
FROM orders
WHERE instrument_id = $1
    AND direction = 'BUY'
    AND exec_report_status = 'FILL'
    AND trader_id = $2
    AND order_id_ref IS NULL
ORDER BY price_units, price_nano
LIMIT 1
`

type GetLowestExecutedBuyOrderParams struct {
	InstrumentID int32
	TraderID     string
}

type GetLowestExecutedBuyOrderRow struct {
	ID               int32
	CreatedAt        sql.NullTime
	CompletedAt      sql.NullTime
	OrderID          string
	Direction        string
	ExecReportStatus string
	PriceUnits       int64
	PriceNano        int32
	LotsRequested    int64
	LotsExecuted     int64
	AdditionalInfo   sql.NullString
}

func (q *Queries) GetLowestExecutedBuyOrder(ctx context.Context, arg GetLowestExecutedBuyOrderParams) (GetLowestExecutedBuyOrderRow, error) {
	row := q.db.QueryRowContext(ctx, getLowestExecutedBuyOrder, arg.InstrumentID, arg.TraderID)
	var i GetLowestExecutedBuyOrderRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.OrderID,
		&i.Direction,
		&i.ExecReportStatus,
		&i.PriceUnits,
		&i.PriceNano,
		&i.LotsRequested,
		&i.LotsExecuted,
		&i.AdditionalInfo,
	)
	return i, err
}

const getUnsoldOrdersAmount = `-- name: GetUnsoldOrdersAmount :one
SELECT COUNT(*) FROM orders
WHERE instrument_id = $1
    AND direction = 'BUY'
    AND trader_id = $2
    AND order_id_ref IS NULL
`

type GetUnsoldOrdersAmountParams struct {
	InstrumentID int32
	TraderID     string
}

func (q *Queries) GetUnsoldOrdersAmount(ctx context.Context, arg GetUnsoldOrdersAmountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnsoldOrdersAmount, arg.InstrumentID, arg.TraderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const setOrderIdRefNull = `-- name: SetOrderIdRefNull :exec
UPDATE orders
SET order_id_ref = NULL
WHERE instrument_id = $1
	AND trader_id = $2
	AND order_id = $3
`

type SetOrderIdRefNullParams struct {
	InstrumentID int32
	TraderID     string
	OrderID      string
}

func (q *Queries) SetOrderIdRefNull(ctx context.Context, arg SetOrderIdRefNullParams) error {
	_, err := q.db.ExecContext(ctx, setOrderIdRefNull, arg.InstrumentID, arg.TraderID, arg.OrderID)
	return err
}
