// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Candle struct {
	ID           int32
	InstrumentID int32
	Timestamp    time.Time
	Interval     string
	OpenUnits    int64
	OpenNano     int32
	CloseUnits   int64
	CloseNano    int32
	HighUnits    int64
	HighNano     int32
	LowUnits     int64
	LowNano      int32
	Volume       int64
}

type Instrument struct {
	ID           int32
	Uid          string
	Isin         string
	Figi         string
	Ticker       string
	ClassCode    string
	Name         string
	Lot          int32
	AvailableApi bool
	ForQuals     bool
}

type MinMaxPrice struct {
	TraderID string
	MaxUnits sql.NullInt64
	MaxNano  sql.NullInt32
	MinUnits sql.NullInt64
	MinNano  sql.NullInt32
}

type Order struct {
	ID               int32
	InstrumentID     int32
	CreatedAt        sql.NullTime
	CompletedAt      sql.NullTime
	OrderID          string
	OrderIDRef       sql.NullString
	Direction        string
	ExecReportStatus string
	PriceUnits       int64
	PriceNano        int32
	LotsRequested    int64
	LotsExecuted     int64
	TraderID         string
	AdditionalInfo   sql.NullString
}
