// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: postgres.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const deleteOrdersForTrader = `-- name: DeleteOrdersForTrader :exec
DELETE FROM orders
WHERE trader_id = $1
`

func (q *Queries) DeleteOrdersForTrader(ctx context.Context, traderID string) error {
	_, err := q.db.ExecContext(ctx, deleteOrdersForTrader, traderID)
	return err
}

const getCandles = `-- name: GetCandles :many
SELECT
    id,
    instrument_id, 
    "timestamp", 
    interval, 
    open_units, 
    open_nano,
    close_units, 
    close_nano, 
    high_units, 
    high_nano,
    low_units, 
    low_nano, 
    volume
FROM candles
WHERE instrument_id = $1
    AND interval = $2
    AND "timestamp" >= $3
    AND "timestamp" <= $4
ORDER BY "timestamp"
`

type GetCandlesParams struct {
	InstrumentID  int32
	Interval      string
	TimestampFrom time.Time
	TimestampTo   time.Time
}

func (q *Queries) GetCandles(ctx context.Context, arg GetCandlesParams) ([]Candle, error) {
	rows, err := q.db.QueryContext(ctx, getCandles,
		arg.InstrumentID,
		arg.Interval,
		arg.TimestampFrom,
		arg.TimestampTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Candle
	for rows.Next() {
		var i Candle
		if err := rows.Scan(
			&i.ID,
			&i.InstrumentID,
			&i.Timestamp,
			&i.Interval,
			&i.OpenUnits,
			&i.OpenNano,
			&i.CloseUnits,
			&i.CloseNano,
			&i.HighUnits,
			&i.HighNano,
			&i.LowUnits,
			&i.LowNano,
			&i.Volume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstrumentInfo = `-- name: GetInstrumentInfo :one
SELECT id, uid, isin, figi, ticker, class_code, name, lot, available_api, for_quals FROM instruments WHERE uid = $1
`

func (q *Queries) GetInstrumentInfo(ctx context.Context, uid string) (Instrument, error) {
	row := q.db.QueryRowContext(ctx, getInstrumentInfo, uid)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Isin,
		&i.Figi,
		&i.Ticker,
		&i.ClassCode,
		&i.Name,
		&i.Lot,
		&i.AvailableApi,
		&i.ForQuals,
	)
	return i, err
}

const insertCandlesBatch = `-- name: InsertCandlesBatch :exec
INSERT INTO candles (
    instrument_id, 
    "timestamp", 
    "interval", 
    open_units, 
    open_nano, 
    close_units, 
    close_nano, 
    high_units, 
    high_nano, 
    low_units, 
    low_nano, 
    volume
)
SELECT 
    unnest($1::int[]),
    unnest($2::timestamptz[]),
    unnest($3::text[]),
    unnest($4::bigint[]),
    unnest($5::int[]),
    unnest($6::bigint[]),
    unnest($7::int[]),
    unnest($8::bigint[]),
    unnest($9::int[]),
    unnest($10::bigint[]),
    unnest($11::int[]),
    unnest($12::bigint[])
ON CONFLICT (instrument_id, "timestamp", "interval") DO NOTHING
`

type InsertCandlesBatchParams struct {
	InstrumentIds []int32
	Timestamps    []time.Time
	Intervals     []string
	OpensUnits    []int64
	OpensNanos    []int32
	ClosesUnits   []int64
	ClosesNanos   []int32
	HighsUnits    []int64
	HighsNanos    []int32
	LowsUnits     []int64
	LowsNanos     []int32
	Volumes       []int64
}

func (q *Queries) InsertCandlesBatch(ctx context.Context, arg InsertCandlesBatchParams) error {
	_, err := q.db.ExecContext(ctx, insertCandlesBatch,
		pq.Array(arg.InstrumentIds),
		pq.Array(arg.Timestamps),
		pq.Array(arg.Intervals),
		pq.Array(arg.OpensUnits),
		pq.Array(arg.OpensNanos),
		pq.Array(arg.ClosesUnits),
		pq.Array(arg.ClosesNanos),
		pq.Array(arg.HighsUnits),
		pq.Array(arg.HighsNanos),
		pq.Array(arg.LowsUnits),
		pq.Array(arg.LowsNanos),
		pq.Array(arg.Volumes),
	)
	return err
}

const insertOrder = `-- name: InsertOrder :exec
INSERT INTO orders 
    (instrument_id, 
    created_at, 
    completed_at,
    order_id, 
    order_id_ref, 
    direction, 
    exec_report_status,
    price_units, 
    price_nano, 
    lots_requested, 
    lots_executed, 
    trader_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
`

type InsertOrderParams struct {
	InstrumentID     int32
	CreatedAt        sql.NullTime
	CompletedAt      sql.NullTime
	OrderID          string
	OrderIDRef       sql.NullString
	Direction        string
	ExecReportStatus string
	PriceUnits       int64
	PriceNano        int32
	LotsRequested    int64
	LotsExecuted     int64
	TraderID         string
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.ExecContext(ctx, insertOrder,
		arg.InstrumentID,
		arg.CreatedAt,
		arg.CompletedAt,
		arg.OrderID,
		arg.OrderIDRef,
		arg.Direction,
		arg.ExecReportStatus,
		arg.PriceUnits,
		arg.PriceNano,
		arg.LotsRequested,
		arg.LotsExecuted,
		arg.TraderID,
	)
	return err
}

const insertinstrumentInfo = `-- name: InsertinstrumentInfo :one
INSERT INTO instruments (uid, isin, figi, ticker, class_code, name, lot, available_api, for_quals)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT (uid, isin, figi, ticker)
DO UPDATE SET 
    lot = EXCLUDED.lot,
    name = EXCLUDED.name,
    available_api = EXCLUDED.available_api,
    for_quals = EXCLUDED.for_quals
RETURNING id
`

type InsertinstrumentInfoParams struct {
	Uid          string
	Isin         string
	Figi         string
	Ticker       string
	ClassCode    string
	Name         string
	Lot          int32
	AvailableApi bool
	ForQuals     bool
}

func (q *Queries) InsertinstrumentInfo(ctx context.Context, arg InsertinstrumentInfoParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertinstrumentInfo,
		arg.Uid,
		arg.Isin,
		arg.Figi,
		arg.Ticker,
		arg.ClassCode,
		arg.Name,
		arg.Lot,
		arg.AvailableApi,
		arg.ForQuals,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateOrder = `-- name: UpdateOrder :exec
UPDATE orders
SET created_at = $1,
    completed_at = $2,
    direction = $3,
    exec_report_status = $4,
    price_units = $5,
    price_nano = $6,
    lots_executed = $7
WHERE instrument_id = $8
AND trader_id = $9
AND order_id = $10
`

type UpdateOrderParams struct {
	CreatedAt        sql.NullTime
	CompletedAt      sql.NullTime
	Direction        string
	ExecReportStatus string
	PriceUnits       int64
	PriceNano        int32
	LotsExecuted     int64
	InstrumentID     int32
	TraderID         string
	OrderID          string
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateOrder,
		arg.CreatedAt,
		arg.CompletedAt,
		arg.Direction,
		arg.ExecReportStatus,
		arg.PriceUnits,
		arg.PriceNano,
		arg.LotsExecuted,
		arg.InstrumentID,
		arg.TraderID,
		arg.OrderID,
	)
	return err
}

const updateOrderRef = `-- name: UpdateOrderRef :exec
UPDATE orders
SET order_id_ref = $1
WHERE instrument_id = $2
AND trader_id = $3
AND order_id = $4
`

type UpdateOrderRefParams struct {
	OrderIDRef   sql.NullString
	InstrumentID int32
	TraderID     string
	OrderID      string
}

func (q *Queries) UpdateOrderRef(ctx context.Context, arg UpdateOrderRefParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderRef,
		arg.OrderIDRef,
		arg.InstrumentID,
		arg.TraderID,
		arg.OrderID,
	)
	return err
}
