// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	DeleteOrderForInstrumentOfTrader(ctx context.Context, arg DeleteOrderForInstrumentOfTraderParams) error
	DeleteOrdersForTrader(ctx context.Context, traderID string) error
	GetCandles(ctx context.Context, arg GetCandlesParams) ([]Candle, error)
	GetHighestExecutedBuyOrder(ctx context.Context, arg GetHighestExecutedBuyOrderParams) (GetHighestExecutedBuyOrderRow, error)
	GetInstrumentInfo(ctx context.Context, uid string) (Instrument, error)
	GetLatestExecutedSellOrder(ctx context.Context, arg GetLatestExecutedSellOrderParams) (GetLatestExecutedSellOrderRow, error)
	GetLowestExecutedBuyOrder(ctx context.Context, arg GetLowestExecutedBuyOrderParams) (GetLowestExecutedBuyOrderRow, error)
	GetMinMaxPrice(ctx context.Context, traderID string) (MinMaxPrice, error)
	GetUnsoldOrdersAmount(ctx context.Context, arg GetUnsoldOrdersAmountParams) (int64, error)
	InsertCandlesBatch(ctx context.Context, arg InsertCandlesBatchParams) error
	InsertOrder(ctx context.Context, arg InsertOrderParams) error
	InsertinstrumentInfo(ctx context.Context, arg InsertinstrumentInfoParams) (int32, error)
	SetOrderIdRefNull(ctx context.Context, arg SetOrderIdRefNullParams) error
	UpdateMaximumPrice(ctx context.Context, arg UpdateMaximumPriceParams) error
	UpdateMinimumPrice(ctx context.Context, arg UpdateMinimumPriceParams) error
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) error
	UpdateOrderRef(ctx context.Context, arg UpdateOrderRefParams) error
}

var _ Querier = (*Queries)(nil)
