// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: simple_trade.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getMinMaxPrice = `-- name: GetMinMaxPrice :one
SELECT trader_id, max_units, max_nano, min_units, min_nano
FROM min_max_price
WHERE trader_id = $1
`

func (q *Queries) GetMinMaxPrice(ctx context.Context, traderID string) (MinMaxPrice, error) {
	row := q.db.QueryRowContext(ctx, getMinMaxPrice, traderID)
	var i MinMaxPrice
	err := row.Scan(
		&i.TraderID,
		&i.MaxUnits,
		&i.MaxNano,
		&i.MinUnits,
		&i.MinNano,
	)
	return i, err
}

const updateMaximumPrice = `-- name: UpdateMaximumPrice :exec
INSERT INTO min_max_price
(trader_id, max_units, max_nano, min_units, min_nano)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (trader_id)
DO UPDATE SET
    max_units = EXCLUDED.max_units,
    max_nano = EXCLUDED.max_nano
`

type UpdateMaximumPriceParams struct {
	TraderID string
	MaxUnits sql.NullInt64
	MaxNano  sql.NullInt32
	MinUnits sql.NullInt64
	MinNano  sql.NullInt32
}

func (q *Queries) UpdateMaximumPrice(ctx context.Context, arg UpdateMaximumPriceParams) error {
	_, err := q.db.ExecContext(ctx, updateMaximumPrice,
		arg.TraderID,
		arg.MaxUnits,
		arg.MaxNano,
		arg.MinUnits,
		arg.MinNano,
	)
	return err
}

const updateMinimumPrice = `-- name: UpdateMinimumPrice :exec
INSERT INTO min_max_price
(trader_id, max_units, max_nano, min_units, min_nano)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (trader_id)
DO UPDATE SET
    min_units = EXCLUDED.min_units,
    min_nano = EXCLUDED.min_nano
`

type UpdateMinimumPriceParams struct {
	TraderID string
	MaxUnits sql.NullInt64
	MaxNano  sql.NullInt32
	MinUnits sql.NullInt64
	MinNano  sql.NullInt32
}

func (q *Queries) UpdateMinimumPrice(ctx context.Context, arg UpdateMinimumPriceParams) error {
	_, err := q.db.ExecContext(ctx, updateMinimumPrice,
		arg.TraderID,
		arg.MaxUnits,
		arg.MaxNano,
		arg.MinUnits,
		arg.MinNano,
	)
	return err
}
