// Code generated by MockGen. DO NOT EDIT.
// Source: trader.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	datastruct "trading_bot/internal/service/datastruct"

	gomock "github.com/golang/mock/gomock"
)

// MockIStrategy is a mock of IStrategy interface.
type MockIStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockIStrategyMockRecorder
}

// MockIStrategyMockRecorder is the mock recorder for MockIStrategy.
type MockIStrategyMockRecorder struct {
	mock *MockIStrategy
}

// NewMockIStrategy creates a new mock instance.
func NewMockIStrategy(ctrl *gomock.Controller) *MockIStrategy {
	mock := &MockIStrategy{ctrl: ctrl}
	mock.recorder = &MockIStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStrategy) EXPECT() *MockIStrategyMockRecorder {
	return m.recorder
}

// GetActionDecision mocks base method.
func (m *MockIStrategy) GetActionDecision(ctx context.Context, instrInfo *datastruct.InstrumentInfo, lp *datastruct.LastPrice) (*StrategyAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActionDecision", ctx, instrInfo, lp)
	ret0, _ := ret[0].(*StrategyAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActionDecision indicates an expected call of GetActionDecision.
func (mr *MockIStrategyMockRecorder) GetActionDecision(ctx, instrInfo, lp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActionDecision", reflect.TypeOf((*MockIStrategy)(nil).GetActionDecision), ctx, instrInfo, lp)
}

// GetName mocks base method.
func (m *MockIStrategy) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockIStrategyMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockIStrategy)(nil).GetName))
}

// MockILogger is a mock of ILogger interface.
type MockILogger struct {
	ctrl     *gomock.Controller
	recorder *MockILoggerMockRecorder
}

// MockILoggerMockRecorder is the mock recorder for MockILogger.
type MockILoggerMockRecorder struct {
	mock *MockILogger
}

// NewMockILogger creates a new mock instance.
func NewMockILogger(ctrl *gomock.Controller) *MockILogger {
	mock := &MockILogger{ctrl: ctrl}
	mock.recorder = &MockILoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILogger) EXPECT() *MockILoggerMockRecorder {
	return m.recorder
}

// Errorf mocks base method.
func (m *MockILogger) Errorf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockILoggerMockRecorder) Errorf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockILogger)(nil).Errorf), varargs...)
}

// Fatalf mocks base method.
func (m *MockILogger) Fatalf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatalf", varargs...)
}

// Fatalf indicates an expected call of Fatalf.
func (mr *MockILoggerMockRecorder) Fatalf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatalf", reflect.TypeOf((*MockILogger)(nil).Fatalf), varargs...)
}

// Infof mocks base method.
func (m *MockILogger) Infof(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockILoggerMockRecorder) Infof(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockILogger)(nil).Infof), varargs...)
}

// MockIBroker is a mock of IBroker interface.
type MockIBroker struct {
	ctrl     *gomock.Controller
	recorder *MockIBrokerMockRecorder
}

// MockIBrokerMockRecorder is the mock recorder for MockIBroker.
type MockIBrokerMockRecorder struct {
	mock *MockIBroker
}

// NewMockIBroker creates a new mock instance.
func NewMockIBroker(ctrl *gomock.Controller) *MockIBroker {
	mock := &MockIBroker{ctrl: ctrl}
	mock.recorder = &MockIBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBroker) EXPECT() *MockIBrokerMockRecorder {
	return m.recorder
}

// GetLastPrice mocks base method.
func (m *MockIBroker) GetLastPrice(instrInfo *datastruct.InstrumentInfo) (*datastruct.LastPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastPrice", instrInfo)
	ret0, _ := ret[0].(*datastruct.LastPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastPrice indicates an expected call of GetLastPrice.
func (mr *MockIBrokerMockRecorder) GetLastPrice(instrInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastPrice", reflect.TypeOf((*MockIBroker)(nil).GetLastPrice), instrInfo)
}

// MakeBuyOrder mocks base method.
func (m *MockIBroker) MakeBuyOrder(instrInfo *datastruct.InstrumentInfo, quantity int64) (*datastruct.PostOrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeBuyOrder", instrInfo, quantity)
	ret0, _ := ret[0].(*datastruct.PostOrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeBuyOrder indicates an expected call of MakeBuyOrder.
func (mr *MockIBrokerMockRecorder) MakeBuyOrder(instrInfo, quantity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeBuyOrder", reflect.TypeOf((*MockIBroker)(nil).MakeBuyOrder), instrInfo, quantity)
}

// MakeSellOrder mocks base method.
func (m *MockIBroker) MakeSellOrder(instrInfo *datastruct.InstrumentInfo, quantity int64) (*datastruct.PostOrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeSellOrder", instrInfo, quantity)
	ret0, _ := ret[0].(*datastruct.PostOrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeSellOrder indicates an expected call of MakeSellOrder.
func (mr *MockIBrokerMockRecorder) MakeSellOrder(instrInfo, quantity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeSellOrder", reflect.TypeOf((*MockIBroker)(nil).MakeSellOrder), instrInfo, quantity)
}
