// Code generated by MockGen. DO NOT EDIT.
// Source: trader.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	datastruct "trading_bot/internal/service/datastruct"

	gomock "github.com/golang/mock/gomock"
)

// MockIStrategy is a mock of IStrategy interface.
type MockIStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockIStrategyMockRecorder
}

// MockIStrategyMockRecorder is the mock recorder for MockIStrategy.
type MockIStrategyMockRecorder struct {
	mock *MockIStrategy
}

// NewMockIStrategy creates a new mock instance.
func NewMockIStrategy(ctrl *gomock.Controller) *MockIStrategy {
	mock := &MockIStrategy{ctrl: ctrl}
	mock.recorder = &MockIStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStrategy) EXPECT() *MockIStrategyMockRecorder {
	return m.recorder
}

// GetActionDecision mocks base method.
func (m *MockIStrategy) GetActionDecision(ctx context.Context, trId string, instrInfo *datastruct.InstrumentInfo, lp *datastruct.LastPrice) (*StrategyAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActionDecision", ctx, trId, instrInfo, lp)
	ret0, _ := ret[0].(*StrategyAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActionDecision indicates an expected call of GetActionDecision.
func (mr *MockIStrategyMockRecorder) GetActionDecision(ctx, trId, instrInfo, lp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActionDecision", reflect.TypeOf((*MockIStrategy)(nil).GetActionDecision), ctx, trId, instrInfo, lp)
}

// GetName mocks base method.
func (m *MockIStrategy) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockIStrategyMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockIStrategy)(nil).GetName))
}

// MockILogger is a mock of ILogger interface.
type MockILogger struct {
	ctrl     *gomock.Controller
	recorder *MockILoggerMockRecorder
}

// MockILoggerMockRecorder is the mock recorder for MockILogger.
type MockILoggerMockRecorder struct {
	mock *MockILogger
}

// NewMockILogger creates a new mock instance.
func NewMockILogger(ctrl *gomock.Controller) *MockILogger {
	mock := &MockILogger{ctrl: ctrl}
	mock.recorder = &MockILoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILogger) EXPECT() *MockILoggerMockRecorder {
	return m.recorder
}

// Errorf mocks base method.
func (m *MockILogger) Errorf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockILoggerMockRecorder) Errorf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockILogger)(nil).Errorf), varargs...)
}

// Fatalf mocks base method.
func (m *MockILogger) Fatalf(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatalf", varargs...)
}

// Fatalf indicates an expected call of Fatalf.
func (mr *MockILoggerMockRecorder) Fatalf(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatalf", reflect.TypeOf((*MockILogger)(nil).Fatalf), varargs...)
}

// Infof mocks base method.
func (m *MockILogger) Infof(template string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{template}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockILoggerMockRecorder) Infof(template interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{template}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockILogger)(nil).Infof), varargs...)
}

// MockIBroker is a mock of IBroker interface.
type MockIBroker struct {
	ctrl     *gomock.Controller
	recorder *MockIBrokerMockRecorder
}

// MockIBrokerMockRecorder is the mock recorder for MockIBroker.
type MockIBrokerMockRecorder struct {
	mock *MockIBroker
}

// NewMockIBroker creates a new mock instance.
func NewMockIBroker(ctrl *gomock.Controller) *MockIBroker {
	mock := &MockIBroker{ctrl: ctrl}
	mock.recorder = &MockIBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBroker) EXPECT() *MockIBrokerMockRecorder {
	return m.recorder
}

// MakeBuyOrder mocks base method.
func (m *MockIBroker) MakeBuyOrder(instrInfo *datastruct.InstrumentInfo, lots int64, requestId string) (*datastruct.PostOrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeBuyOrder", instrInfo, lots, requestId)
	ret0, _ := ret[0].(*datastruct.PostOrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeBuyOrder indicates an expected call of MakeBuyOrder.
func (mr *MockIBrokerMockRecorder) MakeBuyOrder(instrInfo, lots, requestId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeBuyOrder", reflect.TypeOf((*MockIBroker)(nil).MakeBuyOrder), instrInfo, lots, requestId)
}

// MakeSellOrder mocks base method.
func (m *MockIBroker) MakeSellOrder(instrInfo *datastruct.InstrumentInfo, lots int64, requestId string) (*datastruct.PostOrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeSellOrder", instrInfo, lots, requestId)
	ret0, _ := ret[0].(*datastruct.PostOrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeSellOrder indicates an expected call of MakeSellOrder.
func (mr *MockIBrokerMockRecorder) MakeSellOrder(instrInfo, lots, requestId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeSellOrder", reflect.TypeOf((*MockIBroker)(nil).MakeSellOrder), instrInfo, lots, requestId)
}

// RecieveLastPrice mocks base method.
func (m *MockIBroker) RecieveLastPrice(instrInfo *datastruct.InstrumentInfo) (*datastruct.LastPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecieveLastPrice", instrInfo)
	ret0, _ := ret[0].(*datastruct.LastPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecieveLastPrice indicates an expected call of RecieveLastPrice.
func (mr *MockIBrokerMockRecorder) RecieveLastPrice(instrInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecieveLastPrice", reflect.TypeOf((*MockIBroker)(nil).RecieveLastPrice), instrInfo)
}

// RecieveOrdersUpdate mocks base method.
func (m *MockIBroker) RecieveOrdersUpdate(instrInfo *datastruct.InstrumentInfo) (*datastruct.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecieveOrdersUpdate", instrInfo)
	ret0, _ := ret[0].(*datastruct.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecieveOrdersUpdate indicates an expected call of RecieveOrdersUpdate.
func (mr *MockIBrokerMockRecorder) RecieveOrdersUpdate(instrInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecieveOrdersUpdate", reflect.TypeOf((*MockIBroker)(nil).RecieveOrdersUpdate), instrInfo)
}

// MockIStorage is a mock of IStorage interface.
type MockIStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIStorageMockRecorder
}

// MockIStorageMockRecorder is the mock recorder for MockIStorage.
type MockIStorageMockRecorder struct {
	mock *MockIStorage
}

// NewMockIStorage creates a new mock instance.
func NewMockIStorage(ctrl *gomock.Controller) *MockIStorage {
	mock := &MockIStorage{ctrl: ctrl}
	mock.recorder = &MockIStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStorage) EXPECT() *MockIStorageMockRecorder {
	return m.recorder
}

// GetInstrumentInfo mocks base method.
func (m *MockIStorage) GetInstrumentInfo(uid string) (*datastruct.InstrumentInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstrumentInfo", uid)
	ret0, _ := ret[0].(*datastruct.InstrumentInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstrumentInfo indicates an expected call of GetInstrumentInfo.
func (mr *MockIStorageMockRecorder) GetInstrumentInfo(uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstrumentInfo", reflect.TypeOf((*MockIStorage)(nil).GetInstrumentInfo), uid)
}

// PutOrder mocks base method.
func (m *MockIStorage) PutOrder(trId string, instrInfo *datastruct.InstrumentInfo, order *datastruct.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutOrder", trId, instrInfo, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutOrder indicates an expected call of PutOrder.
func (mr *MockIStorageMockRecorder) PutOrder(trId, instrInfo, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutOrder", reflect.TypeOf((*MockIStorage)(nil).PutOrder), trId, instrInfo, order)
}
