// Code generated by MockGen. DO NOT EDIT.
// Source: postgres.go

// Package postgres is a generated GoMock package.
package postgres

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	sqlc "trading_bot/internal/clients/postgres/sqlc"

	gomock "github.com/golang/mock/gomock"
)

// MockIQuerier is a mock of IQuerier interface.
type MockIQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockIQuerierMockRecorder
}

// MockIQuerierMockRecorder is the mock recorder for MockIQuerier.
type MockIQuerierMockRecorder struct {
	mock *MockIQuerier
}

// NewMockIQuerier creates a new mock instance.
func NewMockIQuerier(ctrl *gomock.Controller) *MockIQuerier {
	mock := &MockIQuerier{ctrl: ctrl}
	mock.recorder = &MockIQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIQuerier) EXPECT() *MockIQuerierMockRecorder {
	return m.recorder
}

// DeleteOrderForInstrumentOfTrader mocks base method.
func (m *MockIQuerier) DeleteOrderForInstrumentOfTrader(ctx context.Context, arg sqlc.DeleteOrderForInstrumentOfTraderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderForInstrumentOfTrader", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrderForInstrumentOfTrader indicates an expected call of DeleteOrderForInstrumentOfTrader.
func (mr *MockIQuerierMockRecorder) DeleteOrderForInstrumentOfTrader(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderForInstrumentOfTrader", reflect.TypeOf((*MockIQuerier)(nil).DeleteOrderForInstrumentOfTrader), ctx, arg)
}

// DeleteOrdersForTrader mocks base method.
func (m *MockIQuerier) DeleteOrdersForTrader(ctx context.Context, traderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrdersForTrader", ctx, traderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrdersForTrader indicates an expected call of DeleteOrdersForTrader.
func (mr *MockIQuerierMockRecorder) DeleteOrdersForTrader(ctx, traderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrdersForTrader", reflect.TypeOf((*MockIQuerier)(nil).DeleteOrdersForTrader), ctx, traderID)
}

// GetCandles mocks base method.
func (m *MockIQuerier) GetCandles(ctx context.Context, arg sqlc.GetCandlesParams) ([]sqlc.Candle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCandles", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Candle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCandles indicates an expected call of GetCandles.
func (mr *MockIQuerierMockRecorder) GetCandles(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCandles", reflect.TypeOf((*MockIQuerier)(nil).GetCandles), ctx, arg)
}

// GetHighestExecutedBuyOrder mocks base method.
func (m *MockIQuerier) GetHighestExecutedBuyOrder(ctx context.Context, arg sqlc.GetHighestExecutedBuyOrderParams) (sqlc.GetHighestExecutedBuyOrderRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHighestExecutedBuyOrder", ctx, arg)
	ret0, _ := ret[0].(sqlc.GetHighestExecutedBuyOrderRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHighestExecutedBuyOrder indicates an expected call of GetHighestExecutedBuyOrder.
func (mr *MockIQuerierMockRecorder) GetHighestExecutedBuyOrder(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHighestExecutedBuyOrder", reflect.TypeOf((*MockIQuerier)(nil).GetHighestExecutedBuyOrder), ctx, arg)
}

// GetInstrumentInfo mocks base method.
func (m *MockIQuerier) GetInstrumentInfo(ctx context.Context, uid string) (sqlc.Instrument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstrumentInfo", ctx, uid)
	ret0, _ := ret[0].(sqlc.Instrument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstrumentInfo indicates an expected call of GetInstrumentInfo.
func (mr *MockIQuerierMockRecorder) GetInstrumentInfo(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstrumentInfo", reflect.TypeOf((*MockIQuerier)(nil).GetInstrumentInfo), ctx, uid)
}

// GetLatestExecutedSellOrder mocks base method.
func (m *MockIQuerier) GetLatestExecutedSellOrder(ctx context.Context, arg sqlc.GetLatestExecutedSellOrderParams) (sqlc.GetLatestExecutedSellOrderRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestExecutedSellOrder", ctx, arg)
	ret0, _ := ret[0].(sqlc.GetLatestExecutedSellOrderRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestExecutedSellOrder indicates an expected call of GetLatestExecutedSellOrder.
func (mr *MockIQuerierMockRecorder) GetLatestExecutedSellOrder(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestExecutedSellOrder", reflect.TypeOf((*MockIQuerier)(nil).GetLatestExecutedSellOrder), ctx, arg)
}

// GetLowestExecutedBuyOrder mocks base method.
func (m *MockIQuerier) GetLowestExecutedBuyOrder(ctx context.Context, arg sqlc.GetLowestExecutedBuyOrderParams) (sqlc.GetLowestExecutedBuyOrderRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLowestExecutedBuyOrder", ctx, arg)
	ret0, _ := ret[0].(sqlc.GetLowestExecutedBuyOrderRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLowestExecutedBuyOrder indicates an expected call of GetLowestExecutedBuyOrder.
func (mr *MockIQuerierMockRecorder) GetLowestExecutedBuyOrder(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLowestExecutedBuyOrder", reflect.TypeOf((*MockIQuerier)(nil).GetLowestExecutedBuyOrder), ctx, arg)
}

// GetMinMaxPrice mocks base method.
func (m *MockIQuerier) GetMinMaxPrice(ctx context.Context, traderID string) (sqlc.MinMaxPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinMaxPrice", ctx, traderID)
	ret0, _ := ret[0].(sqlc.MinMaxPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinMaxPrice indicates an expected call of GetMinMaxPrice.
func (mr *MockIQuerierMockRecorder) GetMinMaxPrice(ctx, traderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinMaxPrice", reflect.TypeOf((*MockIQuerier)(nil).GetMinMaxPrice), ctx, traderID)
}

// GetUnsoldOrdersAmount mocks base method.
func (m *MockIQuerier) GetUnsoldOrdersAmount(ctx context.Context, arg sqlc.GetUnsoldOrdersAmountParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnsoldOrdersAmount", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnsoldOrdersAmount indicates an expected call of GetUnsoldOrdersAmount.
func (mr *MockIQuerierMockRecorder) GetUnsoldOrdersAmount(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnsoldOrdersAmount", reflect.TypeOf((*MockIQuerier)(nil).GetUnsoldOrdersAmount), ctx, arg)
}

// InsertCandlesBatch mocks base method.
func (m *MockIQuerier) InsertCandlesBatch(ctx context.Context, arg sqlc.InsertCandlesBatchParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCandlesBatch", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertCandlesBatch indicates an expected call of InsertCandlesBatch.
func (mr *MockIQuerierMockRecorder) InsertCandlesBatch(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCandlesBatch", reflect.TypeOf((*MockIQuerier)(nil).InsertCandlesBatch), ctx, arg)
}

// InsertOrder mocks base method.
func (m *MockIQuerier) InsertOrder(ctx context.Context, arg sqlc.InsertOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrder", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrder indicates an expected call of InsertOrder.
func (mr *MockIQuerierMockRecorder) InsertOrder(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrder", reflect.TypeOf((*MockIQuerier)(nil).InsertOrder), ctx, arg)
}

// InsertinstrumentInfo mocks base method.
func (m *MockIQuerier) InsertinstrumentInfo(ctx context.Context, arg sqlc.InsertinstrumentInfoParams) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertinstrumentInfo", ctx, arg)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertinstrumentInfo indicates an expected call of InsertinstrumentInfo.
func (mr *MockIQuerierMockRecorder) InsertinstrumentInfo(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertinstrumentInfo", reflect.TypeOf((*MockIQuerier)(nil).InsertinstrumentInfo), ctx, arg)
}

// SetOrderIdRefNull mocks base method.
func (m *MockIQuerier) SetOrderIdRefNull(ctx context.Context, arg sqlc.SetOrderIdRefNullParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOrderIdRefNull", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOrderIdRefNull indicates an expected call of SetOrderIdRefNull.
func (mr *MockIQuerierMockRecorder) SetOrderIdRefNull(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOrderIdRefNull", reflect.TypeOf((*MockIQuerier)(nil).SetOrderIdRefNull), ctx, arg)
}

// UpdateMaximumPrice mocks base method.
func (m *MockIQuerier) UpdateMaximumPrice(ctx context.Context, arg sqlc.UpdateMaximumPriceParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMaximumPrice", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMaximumPrice indicates an expected call of UpdateMaximumPrice.
func (mr *MockIQuerierMockRecorder) UpdateMaximumPrice(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMaximumPrice", reflect.TypeOf((*MockIQuerier)(nil).UpdateMaximumPrice), ctx, arg)
}

// UpdateMinimumPrice mocks base method.
func (m *MockIQuerier) UpdateMinimumPrice(ctx context.Context, arg sqlc.UpdateMinimumPriceParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMinimumPrice", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMinimumPrice indicates an expected call of UpdateMinimumPrice.
func (mr *MockIQuerierMockRecorder) UpdateMinimumPrice(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMinimumPrice", reflect.TypeOf((*MockIQuerier)(nil).UpdateMinimumPrice), ctx, arg)
}

// UpdateOrder mocks base method.
func (m *MockIQuerier) UpdateOrder(ctx context.Context, arg sqlc.UpdateOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockIQuerierMockRecorder) UpdateOrder(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockIQuerier)(nil).UpdateOrder), ctx, arg)
}

// UpdateOrderRef mocks base method.
func (m *MockIQuerier) UpdateOrderRef(ctx context.Context, arg sqlc.UpdateOrderRefParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderRef", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderRef indicates an expected call of UpdateOrderRef.
func (mr *MockIQuerierMockRecorder) UpdateOrderRef(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderRef", reflect.TypeOf((*MockIQuerier)(nil).UpdateOrderRef), ctx, arg)
}

// MockIDB is a mock of IDB interface.
type MockIDB struct {
	ctrl     *gomock.Controller
	recorder *MockIDBMockRecorder
}

// MockIDBMockRecorder is the mock recorder for MockIDB.
type MockIDBMockRecorder struct {
	mock *MockIDB
}

// NewMockIDB creates a new mock instance.
func NewMockIDB(ctrl *gomock.Controller) *MockIDB {
	mock := &MockIDB{ctrl: ctrl}
	mock.recorder = &MockIDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDB) EXPECT() *MockIDBMockRecorder {
	return m.recorder
}

// CtxWithCancel mocks base method.
func (m *MockIDB) CtxWithCancel() (context.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CtxWithCancel")
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// CtxWithCancel indicates an expected call of CtxWithCancel.
func (mr *MockIDBMockRecorder) CtxWithCancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CtxWithCancel", reflect.TypeOf((*MockIDB)(nil).CtxWithCancel))
}

// ExecTx mocks base method.
func (m *MockIDB) ExecTx(arg0 *sql.TxOptions, arg1 func(context.Context, IQuerier) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecTx indicates an expected call of ExecTx.
func (mr *MockIDBMockRecorder) ExecTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecTx", reflect.TypeOf((*MockIDB)(nil).ExecTx), arg0, arg1)
}

// Querier mocks base method.
func (m *MockIDB) Querier() IQuerier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Querier")
	ret0, _ := ret[0].(IQuerier)
	return ret0
}

// Querier indicates an expected call of Querier.
func (mr *MockIDBMockRecorder) Querier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Querier", reflect.TypeOf((*MockIDB)(nil).Querier))
}
